apiVersion: v1
data:
  index.html: |
    <html>
      <head>
        <title>K8s Hands-on</title>
      </head>
      <style>
      body {
        font-size: 3em;
      }
      </style>
      <body>
        Your Message: <br>
      </body>
    </html>
  message: hello world
  nginx.conf: |
    server {
        listen       80;
        server_name  _;

        location / {
          root   /usr/share/nginx/html;
          index  index.html;
          sub_filter </body>
              '${MESSAGE}</body>';
          sub_filter_once on;

          auth_basic "Restricted Access";
          auth_basic_user_file /etc/nginx/.htpasswd;
        }

        location ~ /\.ht {
            deny  all;
        }
    }
kind: ConfigMap
metadata:
  name: nginx-config
