apiVersion: v1
kind: Pod
metadata:
  name: tls-nginx
  labels:
    app: tls-nginx
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 443
    volumeMounts:
    - name: tls
      mountPath: /etc/nginx/certs
      readOnly: true
    - name: nginx-config
      mountPath: /etc/nginx/templates/default.conf.template
      subPath: nginx.conf
  volumes:
  - name: nginx-config
    configMap:
      name: nginx-config
  - name: tls
    secret:
      secretName: selfsigned-cert-tls
